name: CI

on: push

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: swift test

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: swift test
